--회원 번호 (PK)
--회원 이름
--회원 아이디 (UNIQUE)
--회원 패스워드
--회원 생성일자
CREATE TABLE MEMBER (
	M_NO NUMBER PRIMARY KEY,
	M_NAME VARCHAR2(30) NOT NULL,
	M_ID VARCHAR2(50) UNIQUE NOT NULL,
	M_PWD VARCHAR2(255) NOT NULL,
	M_INDATE DATE DEFAULT SYSDATE NOT NULL
);

--포트폴리오 번호 (PK)
--포트폴리오 제목
--포트폴리오 내용
--포트폴리오 내용
--포트폴리오 작성일
--포트폴리오 작성자 (FK)
CREATE TABLE PORTFOLIO (
	P_NO NUMBER PRIMARY KEY,
	P_TITLE VARCHAR2(300) NOT NULL,
	P_CONTENT CLOB NOT NULL,
	P_INDATE DATE DEFAULT SYSDATE NOT NULL,
	M_NO NUMBER REFERENCES MEMBER(M_NO)
);

--게시판 번호 (PK)
--게시판 제목
--게시판 내용
--게시판 조회수
--게시판 등록일
--게시판 수정일
--게시판 삭제일
--게시판 삭제여부 (Y/N)
--게시판 작성자 (FK)
CREATE TABLE FREE_BOARD(
	FB_NO NUMBER PRIMARY KEY,
	FB_TITLE VARCHAR2(300) NOT NULL,
	FB_CONTENT CLOB NOT NULL,
	FB_VIEWS NUMBER DEFAULT 0 NOT NULL,
	FB_INDATE DATE DEFAULT SYSDATE NOT NULL,
	FB_UPDATE DATE DEFAULT SYSDATE,
	FB_DELETE DATE DEFAULT SYSDATE,
	FB_DELETE_STATUS VARCHAR2(1) DEFAULT 'N' CHECK (FB_DELETE_STATUS IN('Y', 'N')) NOT NULL,
	M_NO NUMBER REFERENCES MEMBER(M_NO)
);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE PORTFOLIO_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE FREE_BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
